"""refactor sales into sale items

Revision ID: 3ab92c46fff0
Revises: 433e0979c4e2
Create Date: 2026-08-13 22:10:06.462626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab92c46fff0'
down_revision: Union[str, Sequence[str], None] = '433e0979c4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('sales_product_id_fkey'), 'sales', type_='foreignkey')
    op.drop_column('sales', 'quantity')
    op.drop_column('sales', 'product_id')
    op.drop_column('sales', 'unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sales', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sales_product_id_fkey'), 'sales', 'products', ['product_id'], ['id'])
    op.drop_table('sale_items')
    # ### end Alembic commands ###
