"""add customer date index

Revision ID: e2c01d53e7e0
Revises: 4f07cd905693
Create Date: 2026-09-27 19:46:55.843716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c01d53e7e0'
down_revision: Union[str, Sequence[str], None] = '4f07cd905693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sales_customer_date', 'sales', ['customer_id', 'sale_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_customer_date', table_name='sales')
    # ### end Alembic commands ###
